tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("list/", views.TaskListView.as_view(), name="list"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("complete/<int:uid>", views.complete_task, name="complete"),
    path("delete/<int:uid>", views.delete_task, name="delete"),
    path("details/<int:pk>", views.TaskDetailsView.as_view(), name="details"),
    path("edit/<int:pk>", views.TaskEditView.as_view(), name="edit"),
    path("export/", views.TaskExportView.as_view(), name="export"),
    path("sort/", views.TaskListViewSort.as_view(), name="sort"),
]

todoapp/urls.py
'''Тут хранятся все пути проекта'''
from django.contrib import admin
from django.urls import include, path

from django.conf import settings # чтобы работали картинки
from django.conf.urls.static import static

urlpatterns = [
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # чтобы работали картинки

tasks/models.py
'''models.py описывает схемы базы данных для этого приложения'''

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "Высокий приоритет"),
        (PRIORITY_MEDIUM, "Средний приоритет"),
        (PRIORITY_LOW, "Низкий приоритет"),
    ]

    description = models.CharField(max_length=64)
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey( # владелец задачи
        User,
        on_delete=models.CASCADE, # при удалении пользователя удалятся и задачи
        related_name='tasks')
    priority = models.IntegerField( # приоритет задачи
        "Приоритет",
        choices=PRIORITY_CHOICES,
        default=PRIORITY_MEDIUM)

    def __str__(self):
        return self.description.lower()

#даем django понять, что одно из этих полей будет использовано для сортировки.
#Мы задаем порядок сортировки в поле ordering в специальном подклассе Meta.
    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self): #добавляем в админку кнопку "view on site"
        return reverse("tasks:details", args=[self.pk])

tasks/forms.py
from django import forms
from tasks.models import TodoItem


class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label="")

'''Чтобы создать форму из модели, надо создать класс, наследующийся от django.forms.ModelForm
и ему в Meta указать модель, на базе которой будет строиться форма.
В Meta ещё указываются поля, которые эта форма заполняет. Мы оставим только description.'''
class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ("description", "priority")
        labels = {"description": "Описание", "priority": ""}

class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(
        label="высокая важность", initial=True, required=False
    )
    prio_med = forms.BooleanField(
        label="средней важности", initial=True, required=False
    )
    prio_low = forms.BooleanField(
        label="низкой важности", initial=False, required=False
    )

tasks/views.py
'''views.py описывает основную логику работы с этим приложениям,
по идее здесь должны быть все обработчики http запросов, которые обрабатывают их и возвращают ответ'''
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tasks.models import TodoItem
from tasks.forms import AddTaskForm, TodoItemForm, TodoItemExportForm
from django.views import View
from django.views.generic import ListView
from django.urls import reverse #нужно чтобы использовать имена путей вместо полного пути
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.mail import send_mail #функция для отправки почты, использует настройки из settings
from django.conf import settings

from django.contrib import messages #для отправки сообщений в шаблон base.html

from django.db.models import Q # Объект Q используют, когда нужна какая-то более-менее сложная бинарная логика

from datetime import datetime as dt
a = dt.now().hour + 3
if a >= 6 and a <= 11:
    vremya_s = 'Кстати, какой там у нас сейчас час по Москве? - ' + str(a) + '. Доброе утро! Пей кофе и принимайся за дела!'
    fcolor = 'IndianRed'
elif a >= 12 and a <= 17:
    vremya_s = 'Кстати, какой там у нас сейчас час по Москве? - ' + str(a) + '. Добрый день! Самое время сделать все дела!'
    fcolor = 'SpringGreen'
elif a >= 18 and a <= 24:
    vremya_s = 'Кстати, какой там у нас сейчас час по Москве? - ' + str(a) + '. Добрый вечер! Не ложись спать пока не выполнишь все дела!'
    fcolor = 'MediumAquamarine'
else:
    vremya_s = 'Кстати, какой там у нас сейчас час по Москве? - ' + str(a) + '. Доброй ночи! Спать некогда, делай дела!'
    fcolor = 'DarkSlateGray'


@login_required
def index(request):
    return HttpResponse("Функция index возвращает это сообщение с помощтю HttpResponse в ответ на request по адресу /tasks")

class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):
        u = self.request.user
        qs = super().get_queryset()
        return qs.filter(owner=u)

    def get_context_data(self, *args, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        context['vremya_s'] = vremya_s
        context['fcolor'] = fcolor
        return context

class TaskDetailsView(DetailView): #наследуется из DetailView. Получает объект {{ object }} и засовывает его в шаблон
    model = TodoItem
    template_name = 'tasks/details.html'

class TaskCreateView(View): #создаем класс, наследуемый из View
    def my_render(self, request, form):
        return render(request, "tasks/create.html", {"form": form})

    def post(self, request, *args, **kwargs): #функция ответа при запросе HTTP POST
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            messages.success(request, 'задача добавлена')
            return redirect(reverse("tasks:list"))

        return self.my_render(request, form)

    def get(self, request, *args, **kwargs): #функция ответа при запросе HTTP GET
        form = TodoItemForm()
        return self.my_render(request, form)



def complete_task(request, uid): # path('complete/<int:uid>', views.complete_task, name='complete')
    t = TodoItem.objects.get(id=uid)
    t.is_completed = True
    t.save()
    messages.success(request, "задача выполнена")
    return redirect(reverse("tasks:list"))

def delete_task(request, uid): # path('delete/<int:uid>', views.delete_task, name='delete')
    t = TodoItem.objects.get(id=uid)
    t.delete()
    messages.success(request, "задача удалена") # выводим сообщение в шаблон base.html
    return redirect(reverse("tasks:list"))

class TaskEditView(LoginRequiredMixin, View): # редактирование задачи
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            messages.success(request, 'задача изменена')
            return redirect(reverse("tasks:list"))

        return render(request, "tasks/edit.html", {"form": form, "task": t})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, "tasks/edit.html", {"form": form, "task": t})

#send_mail("Привет от django", "Письмо отправленное из приложения", settings.EMAIL_HOST_USER, ["v.sizov@enesi.ru"], fail_silently=False)

class TaskExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities["prio_high"]:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities["prio_med"]:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities["prio_low"]:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = "Ваши задачи и приоритеты:\n"
        for t in list(tasks):
            if t.is_completed:
                body += f"[x] {t.description} ({t.get_priority_display()})\n"
            else:
                body += f"[ ] {t.description} ({t.get_priority_display()})\n"

        return body

    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail("Задачи", body, settings.EMAIL_HOST_USER, [email])
            messages.success(
                request, "Задачи были отправлены на почту %s" % email)
        else:
            messages.error(request, "Что-то пошло не так, попробуйте ещё раз")
        return redirect(reverse("tasks:list"))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, "tasks/export.html", {"form": form})

class TaskListViewSort(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = "tasks"
    template_name = "tasks/list.html"

    def get_queryset(self):
        u = self.request.user
        qs = super().get_queryset().order_by('priority')
        return qs.filter(owner=u)

    def get_context_data(self, *args, **kwargs):
        context = super(TaskListViewSort, self).get_context_data(**kwargs)
        context['vremya_s'] = vremya_s
        context['fcolor'] = fcolor
        return context

tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Создать задачу{% endblock %}

{% block main_content %}
	<h2>cоздать задачу</h2>
	<form action="." method="post">
    	{{ form.as_p }}
    	{% csrf_token %}
    	<p><button class="add" type="submit">добавить</button></p>
	</form>
	<p></p>
	<a href={% url "tasks:list" %}>отмена</a>
{% endblock %}

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задача {{ object.id }}{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}

{% block main_content %}
  <h2>задача</h2>
  <p><b>описание</b>: {{ object }}</p>
  <ul>
    <li>
      {{ object.is_completed|yesno:"выполнена,не выполнена" }}
    </li>
    <li><i class="far fa-calendar-alt"></i>&nbsp;создана: {{ object.created|date:"Y-b-d H:i" }}</li>
    <li><i class="far fa-clock"></i>&nbsp;последнее изменение: {{ object.updated|date:"Y-b-d H:i" }}</li>
    <li><i class="far fa-edit"></i>&nbsp;<a href="{% url "tasks:edit" pk=object.pk %}">редактировать</a></li>
  </ul>
  <i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url "tasks:list" %}">назад к списку</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block title %}Изменить задачу{% endblock %}

{% block main_content %}
  <h2>поменять задачу</h2>
  <form action="{% url "tasks:edit" task.pk %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">сохранить</button></p>
  </form>
{% endblock %}

tasks/templates/tasks/export.html
{% extends "base.html" %}

{% block title %}Экспорт{% endblock %}

{% block main_content %}
  <h2>экспорт задач</h2>
  <p>на вашу почту придёт емейл с задачами. Уточните список.</p>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Жмяк</button></p>
  </form>
{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block extra_head %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block main_content %}
  <h2>сделай:</h2>
  <form action={% url "tasks:list" %} class="f1">
      <button class="filtr" id="vse_zadachi" type="submit">все задачи</button>
  </form>
  <form action={% url "tasks:sort" %} class="f1">
      <button class="filtr" id="po_prioritetu" type="submit">по приоритету</button>
  </form>
  <button class="filtr" id="needtodo" type="submit">только невыполненные</button>
  <hr>
  <ul id="todo-list">
    {% for task in tasks %}
      {% if task.is_completed %}
        <li class="completed">
        <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
      {% else %}
        <li>
        <input class='checkbox' data-uid={{ task.id }} type='checkbox' />
      {% endif %}
      {% if task.priority == task.PRIORITY_HIGH %}
        <span class="badge badge-pill badge-danger">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_MEDIUM %}
        <span class="badge badge-pill badge-secondary">&nbsp;</span>
      {% elif task.priority == task.PRIORITY_LOW %}
        <span class="badge badge-pill badge-success">&nbsp;</span>
      {% endif %}
      <a href={% url "tasks:details" task.id %}>{{ task }}</a>
      <span id="vremya">создана: {{ task.created|timesince }}</span>
      <a class="remove" data-uid={{ task.id }} href={% url "tasks:delete" task.id %}>X</a>
      <hr/>
      </li>
    {% endfor %}
    </ul>
    <p><a href={% url "tasks:create" %}> + добавить задачу</a></p>
    <i class="fa fa-download"></i>&nbsp;<a href="{% url "tasks:export" %}">отправить на почту</a>
    <p></p>
{% endblock %}